# Generated by Django 3.1.1 on 2020-11-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201105_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
